In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip


In [13]:
import numpy as np

arr1 = np.array([1,2,3,4,25])

print(arr1)
print(type(arr1))
print(arr1.shape)
np.arange(0,10,2).reshape(5,1)

[ 1  2  3  4 25]
<class 'numpy.ndarray'>
(5,)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
## indentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))

[1.         1.41421356 1.73205081 2.         5.        ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 7.20048993e+10]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.13235175]
